version: "3.9"

services:
  frontend:
    container_name: site
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_RAILS_URL=http://host.docker.internal:3333
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
